DELETE DATABASE IF EXISTS MASTER_PYTHON;
CREATE DATABASE IF NOT EXISTS MASTER_PYTHON;
USE MASTER_PYTHON;

CREATE TABLE IF NOT EXISTS USUARIOS (
    ID INT(25) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(100),
    APELLIDOS VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    FECHA DATETIME NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE NOTAS (
    ID INT(25) AUTO_INCREMENT NOT NULL,
    USUARIO_ID INT(25) NOT NULL,
    TITULO VARCHAR(255) NOT NULL,
    DESCRIPCION MEDIUMTEXT NOT NULL,
    FECHA DATETIME NOT NULL,
    CONSTRAINT PK_NOTAS PRIMARY KEY (ID),
    CONSTRAINT FK_NOTAS_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
    )ENGINE=InnoDB DEFAULT CHARSET=utf8;